"""
Static Taipei Metro (台北捷運) line/station data for the schematic route map.

Station order follows the real line sequence; interchange stations share the
exact same Chinese name across lines (e.g. "中山" on both Red and Green), which
is what the frontend/backend use to identify "the same station" when a user
clicks it from either line's row.

Source: zh.wikipedia.org line articles (fetched 2026-07-11). Not geographically
accurate -- this is a schematic map, matching how real transit maps work.
"""

LINES = [
    {
        "id": "red",
        "name": "淡水信義線",
        "color": "#e3002c",
        "stations": [
            {"code": "R28", "name": "淡水"},
            {"code": "R27", "name": "紅樹林"},
            {"code": "R26", "name": "竹圍"},
            {"code": "R25", "name": "關渡"},
            {"code": "R24", "name": "忠義"},
            {"code": "R23", "name": "復興崗"},
            {"code": "R22", "name": "北投"},
            {"code": "R22A", "name": "新北投"},
            {"code": "R21", "name": "奇岩"},
            {"code": "R20", "name": "唭哩岸"},
            {"code": "R19", "name": "石牌"},
            {"code": "R18", "name": "明德"},
            {"code": "R17", "name": "芝山"},
            {"code": "R16", "name": "士林"},
            {"code": "R15", "name": "劍潭"},
            {"code": "R14", "name": "圓山"},
            {"code": "R13", "name": "民權西路"},
            {"code": "R12", "name": "雙連"},
            {"code": "R11", "name": "中山"},
            {"code": "R10", "name": "台北車站"},
            {"code": "R09", "name": "台大醫院"},
            {"code": "R08", "name": "中正紀念堂"},
            {"code": "R07", "name": "東門"},
            {"code": "R06", "name": "大安森林公園"},
            {"code": "R05", "name": "大安"},
            {"code": "R04", "name": "信義安和"},
            {"code": "R03", "name": "台北101/世貿"},
            {"code": "R02", "name": "象山"},
        ],
    },
    {
        "id": "green",
        "name": "松山新店線",
        "color": "#008659",
        "stations": [
            {"code": "G19", "name": "松山"},
            {"code": "G18", "name": "南京三民"},
            {"code": "G17", "name": "台北小巨蛋"},
            {"code": "G16", "name": "南京復興"},
            {"code": "G15", "name": "松江南京"},
            {"code": "G14", "name": "中山"},
            {"code": "G13", "name": "北門"},
            {"code": "G12", "name": "西門"},
            {"code": "G11", "name": "小南門"},
            {"code": "G10", "name": "中正紀念堂"},
            {"code": "G09", "name": "古亭"},
            {"code": "G08", "name": "台電大樓"},
            {"code": "G07", "name": "公館"},
            {"code": "G06", "name": "萬隆"},
            {"code": "G05", "name": "景美"},
            {"code": "G04", "name": "大坪林"},
            {"code": "G03", "name": "七張"},
            {"code": "G03A", "name": "小碧潭"},
            {"code": "G02", "name": "新店區公所"},
            {"code": "G01", "name": "新店"},
        ],
    },
    {
        "id": "blue",
        "name": "板南線",
        "color": "#0070bd",
        "stations": [
            {"code": "BL01", "name": "頂埔"},
            {"code": "BL02", "name": "永寧"},
            {"code": "BL03", "name": "土城"},
            {"code": "BL04", "name": "海山"},
            {"code": "BL05", "name": "亞東醫院"},
            {"code": "BL06", "name": "府中"},
            {"code": "BL07", "name": "板橋"},
            {"code": "BL08", "name": "新埔"},
            {"code": "BL09", "name": "江子翠"},
            {"code": "BL10", "name": "龍山寺"},
            {"code": "BL11", "name": "西門"},
            {"code": "BL12", "name": "台北車站"},
            {"code": "BL13", "name": "善導寺"},
            {"code": "BL14", "name": "忠孝新生"},
            {"code": "BL15", "name": "忠孝復興"},
            {"code": "BL16", "name": "忠孝敦化"},
            {"code": "BL17", "name": "國父紀念館"},
            {"code": "BL18", "name": "市政府"},
            {"code": "BL19", "name": "永春"},
            {"code": "BL20", "name": "後山埤"},
            {"code": "BL21", "name": "昆陽"},
            {"code": "BL22", "name": "南港"},
            {"code": "BL23", "name": "南港展覽館"},
        ],
    },
    {
        "id": "orange",
        "name": "中和新蘆線",
        "color": "#f8b61c",
        "stations": [
            {"code": "O01", "name": "南勢角"},
            {"code": "O02", "name": "景安"},
            {"code": "O03", "name": "永安市場"},
            {"code": "O04", "name": "頂溪"},
            {"code": "O05", "name": "古亭"},
            {"code": "O06", "name": "東門"},
            {"code": "O07", "name": "忠孝新生"},
            {"code": "O08", "name": "松江南京"},
            {"code": "O09", "name": "行天宮"},
            {"code": "O10", "name": "中山國小"},
            {"code": "O11", "name": "民權西路"},
            {"code": "O12", "name": "大橋頭"},
            {"code": "O13", "name": "台北橋"},
            {"code": "O14", "name": "菜寮"},
            {"code": "O15", "name": "三重"},
            {"code": "O16", "name": "先嗇宮"},
            {"code": "O17", "name": "頭前庄"},
            {"code": "O18", "name": "新莊"},
            {"code": "O19", "name": "輔大"},
            {"code": "O20", "name": "丹鳳"},
            {"code": "O21", "name": "迴龍"},
            {"code": "O50", "name": "三重國小"},
            {"code": "O51", "name": "三和國中"},
            {"code": "O52", "name": "徐匯中學"},
            {"code": "O53", "name": "三民高中"},
            {"code": "O54", "name": "蘆洲"},
        ],
    },
    {
        "id": "brown",
        "name": "文湖線",
        "color": "#c48c31",
        "stations": [
            {"code": "BR01", "name": "動物園"},
            {"code": "BR02", "name": "木柵"},
            {"code": "BR03", "name": "萬芳社區"},
            {"code": "BR04", "name": "萬芳醫院"},
            {"code": "BR05", "name": "辛亥"},
            {"code": "BR06", "name": "麟光"},
            {"code": "BR07", "name": "六張犁"},
            {"code": "BR08", "name": "科技大樓"},
            {"code": "BR09", "name": "大安"},
            {"code": "BR10", "name": "忠孝復興"},
            {"code": "BR11", "name": "南京復興"},
            {"code": "BR12", "name": "中山國中"},
            {"code": "BR13", "name": "松山機場"},
            {"code": "BR14", "name": "大直"},
            {"code": "BR15", "name": "劍南路"},
            {"code": "BR16", "name": "西湖"},
            {"code": "BR17", "name": "港墘"},
            {"code": "BR18", "name": "文德"},
            {"code": "BR19", "name": "內湖"},
            {"code": "BR20", "name": "大湖公園"},
            {"code": "BR21", "name": "葫洲"},
            {"code": "BR22", "name": "東湖"},
            {"code": "BR23", "name": "南港軟體園區"},
            {"code": "BR24", "name": "南港展覽館"},
        ],
    },
    {
        "id": "yellow",
        "name": "環狀線",
        "color": "#ffdb00",
        "stations": [
            {"code": "Y07", "name": "大坪林"},
            {"code": "Y08", "name": "十四張"},
            {"code": "Y09", "name": "秀朗橋"},
            {"code": "Y10", "name": "景平"},
            {"code": "Y11", "name": "景安"},
            {"code": "Y12", "name": "中和"},
            {"code": "Y13", "name": "橋和"},
            {"code": "Y14", "name": "中原"},
            {"code": "Y15", "name": "板新"},
            {"code": "Y16", "name": "板橋"},
            {"code": "Y17", "name": "新埔民生"},
            {"code": "Y18", "name": "頭前庄"},
            {"code": "Y19", "name": "幸福"},
            {"code": "Y20", "name": "新北產業園區"},
        ],
    },
]


def all_station_names() -> list[str]:
    """Unique station names across every line, in first-seen order."""
    seen: dict[str, None] = {}
    for line in LINES:
        for st in line["stations"]:
            seen.setdefault(st["name"], None)
    return list(seen.keys())
